//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace WebApplication13.Models
{
  
    public partial class Order
    {
        public int UserId { get; set; }
        public string Orderstatus { get; set; }
        public int? Orderamount { get; set; }
    
        public virtual User User { get; set; }
    }
}
