//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class User
    {
        public int Userid { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Loginname { get; set; }
        public string Password { get; set; }
    }
}
